### PR TITLE
Redesign playlist page

### PR DESCRIPTION
**Pull request by DavidRobertAnsart**

### CODE REVIEW

**Comment by 2016floreza** [comment]
image

**Comment by 2016floreza** [comment]
Personaly, I find it strange that the whole page is not used. Maybe it can be resolve with more space or bigger cards

**Comment by DavidRobertAnsart** [comment]
Desktop:
Capture d’écran 2020-01-22 à 15 56 33

**Comment by DavidRobertAnsart** [comment]
Phone:
localhost_3000_playlists(iPhone X)

**Comment by DavidRobertAnsart** [comment]
> Personaly, I find it strange that the whole page is not used. Maybe it can be resolve with more space or bigger cards

The whole page is used. See my screen. You just don't have many playlists cards that fill yours.

**Pull request merged**
